---
#################################################
#
# code : 2_system_check.yaml
# function : check RHEL by TWGCB rules
# version : 0.1
#
#################################################

### task part
- hosts: rhel
  gather_facts: true
  become: true
  tasks:
    - name: Include vars of rules-var.yaml for twgcb common variables
      include_vars:
        file: vars/rules-var.yaml

    - name: Include vars of taishinbank-var.yaml for taishinbank related variables
      include_vars:
        file: vars/taishinbank-var.yaml

    # create default worker node status dictionary variable
    - name: create default dictionary variable
      set_fact:
        check_status:  "{{ check_status  | default({}) | combine({ item.id:check_mode[item.id] }) }}"
        check_results: "{{ check_results | default({}) | combine({ item.id:'' }) }}"
      with_items: "{{ rules }}"

    # - debug:
    #     var: check_status

    # - debug:
    #     var: check_results

    - name: set start time
      set_fact:
        var_start_time: "{{ now(fmt='%F %T %A') }}"

    - include_role:
        name: twgcb/system_config_and_maintain/check
    
    - name: set end time
      set_fact:
        var_end_time: "{{ now(fmt='%F %T %A') }}"

    - name: Create reports
      become: no
      template:
        src: check_report.html.j2
        dest: "/tmp/{{ inventory_hostname }}_check_report.html"
        mode: '0644'
      delegate_to: localhost

...
